### ISSUE TITLE
WebdavDocumentUpload field doesn't work

### ISSUE THREAD

**Issue by glebshalyganov** [Haulmont/jmix-webdav-public#17]
Jmix version: 1.1.0

The screen containing the WebdavDocumentUpload field doesn't open and the error occurs:
```xml
        <form id="form" dataContainer="contractDc">
            <column width="350px">
                <textField id="numberField" property="number"/>
                <webdavDocumentUpload id="documentField" property="document"/>
            </column>
        </form>
```
```
java.lang.IllegalArgumentException: FileStorageUploadField doesn't support properties with association
    at io.jmix.ui.component.impl.AbstractFileStorageUploadField.valueBindingConnected(AbstractFileStorageUploadField.java:70)
    at io.jmix.ui.component.impl.AbstractValueComponent.setValueSource(AbstractValueComponent.java:58)
    at io.jmix.ui.xml.layout.loader.AbstractComponentLoader.lambda$loadContainer$0(AbstractComponentLoader.java:842)
    at java.util.Optional.ifPresent(Optional.java:159)
```
The root cause of the issue is the restriction introduced in https://github.com/Haulmont/jmix-ui/issues/314.
Now `AbstractFileStorageUploadField` doesn't allow binding to other types than FileRef.
But `WebdavDocumentUploadFieldImpl` uses `WebdavDocument` as a reference to a file instead of `FileRef`.

It's better off to move type checking from abstract class to the implementation, which is `FileStorageUploadFieldImpl`.

**Comment by owlet1997** [comment]
**TC:**
1. Clone https://github.com/jmix-projects/webdav-demo project -> Start app
2. Open `WD's with enabled versioning` screen
3. Create new instance of the entity
4. Edit the instance -> Upload a new file -> Choose `Create new version` -> Save

**AR:**
 `name` attribute is created from `id` attribute instead of real filename:
![image](https://user-images.githubusercontent.com/45730069/142361895-a48c15bc-937f-4875-802a-f73b2779e66b.png)

![image](https://user-images.githubusercontent.com/45730069/142361870-05aaf9d9-ad18-463f-9df0-39726b24a4c3.png)

**Comment by glebshalyganov** [comment]
@owlet1997, `name` is more of a technical attribute, i.e. it doesn't supposed to be exposed in UI. Instead, `WebdavDocumentLink` should be used in this column (by analogy with the column in DocumentBrowser).
What about the id-name, it happened because you'd uploaded 2 documents with the same name in the same dir (root dir). And by default, the addon generates this `{id}.ext` name in order to maintain uniqueness of the `fullPath`. 
So it is a correct behaviour.
